export { UsersTab } from './UsersTab'
export { PatientsTab } from './PatientsTab'
export { DoctorsTab } from './DoctorsTab'
export { StaffTab } from './StaffTab'
export { AppointmentsTab } from './AppointmentsTab'
export { MedicalRecordsTab } from './MedicalRecordsTab'
export { BillingTab } from './BillingTab'
export { MedicineTab } from './MedicineTab'
export { PharmacyTab } from './PharmacyTab'
export { BloodBankTab } from './BloodBankTab'
export { RoomsTab } from './RoomsTab'
export { RoomAssignmentsTab } from './RoomAssignmentsTab'
export { CleaningTab } from './CleaningTab'
export { AmbulancesTab } from './AmbulancesTab'
export { ReportsTab } from './ReportsTab'
export { HelpTab } from './HelpTab'

